### ISSUE TITLE
sz-magazin.sueddeutsche.de sz-plus Login

### ISSUE THREAD

**Issue by RogerSik** [fivefilters/ftr-site-config#1016]
The sz-magazin.sueddeutsche.de.txt does not provide a login for their sz-plus subscription. 

Example article: https://sz-magazin.sueddeutsche.de/wissen/therapie-psychologie-weisheit-lebenshilfe-92039

I tried to extend it with
```
requires_login: yes

login_uri: https://id.sueddeutsche.de/login
login_username_field: example@example.org
login_password_field: XXX

not_logged_in_xpath: //body[@class="not-logged-in"]
````

but the article above is still not full fetched. Any help is appreciated.

**Comment by HolgerAusB** [comment]
´The login_parameters are not for Filltext RSS at the moment. It is only used by Wallabag. And there you musst not pack your credentials into the config. That will do wallbag for you.

**Comment by RogerSik** [comment]
Ops wrong project created the issue. Sorry!
