### ISSUE TITLE
Fix tags when styled by CSS instead of using semantic HTML

### ISSUE THREAD

**Issue by digicommons** [fivefilters/ftr-site-config#1117]
Some websites don't use proper semantic HTML, which can lead to losing relevant formatting when using FTR. This is most apparent with interviews where a question is formatted differently from an answer with CSS (using `font-weight`/`font-style` instead of `<strong>` or `<em>`).

Is it possible to replace say `<p class="bold">...</p>` with `<strong>...</strong>`? Using `replace_string` seems not to work here, as the closing tag needs to be targeted as well.

**Comment by HolgerAusB** [comment]
That should work, if the class-attribute is really the first one after the `<p`:

```
find_string: <p class="bold"
replace_string: <strong
```
The closing tag should be handled automatically, while user fivefilters doesn't trust this. Maybe yiu want to give us an example URL?

**Comment by digicommons** [comment]
Unfortunately, in the case of [this](https://www.seznamzpravy.cz/clanek/zahranicni-rusko-se-zasadne-meni-analytik-hodnoti-prigozinovu-rebelii-233151) Seznam Zprávy article the replacing doesn't work as desired. Instead of just targeting bold spans with the class `e_ac`, all subsequent `<span>` tags are substituted with `<strong>` as well.

I am using the following config:
```
find_string: <span class="e_ac"
replace_string: <strong
```

**Comment by HolgerAusB** [comment]
AFAIK Wallabag removes/replaces ALL span-tags. That is a problem on many sites

**Comment by digicommons** [comment]
You are right, just confirmed this behavior. Closing as this is an issue of Wallabag and/or [php-readability](https://github.com/j0k3r/php-readability)

**Comment by digicommons** [comment]
Adding `tidy: no` ([docs](https://help.fivefilters.org/full-text-rss/site-patterns.html#tidy-yes-no)) solved the issue in the case of the website mentioned above.

**Comment by HolgerAusB** [comment]
@digicommons, nice to know, thanks.
I did some aditional tweaks, because the main/top image was missing
