### ISSUE TITLE
habr.com spoiler issue

### ISSUE THREAD

**Issue by QuAzI** [fivefilters/ftr-site-config#1432]
Content under spoilers missed
Page from example: https://habr.com/ru/articles/818809/

![image](https://github.com/user-attachments/assets/843a83a8-48bd-4365-ada0-8ff4168e2d89)

**Comment by QuAzI** [comment]
And some bullets missed too
![image](https://github.com/user-attachments/assets/6777d306-c977-47b9-a020-1ba9f41d60dd)
https://habr.com/ru/articles/843288/

**Comment by HolgerAusB** [comment]
OK, @QuAzI these are different issues.

1.)
Your first post does not belong to this repo. As Fivefilter's FullText-RSS is indeed [showing the spoiler part](https://ftr.fivefilters.net/makefulltextfeed.php?step=3&fulltext=1&url=https%3A%2F%2Fhabr.com%2Fru%2Farticles%2F818809%2F&max=3&links=preserve&exc=&submit=Create+Feed). Your issue should go to the [wallabag repo](https://github.com/wallabag/wallabag/issues): I don't see a reason why the content of the `<details>` element is striped off from the catch by wallabag.

I can make it visible, but not hidden behind the spoiler line. It would be normal text or maybe in a blockquote if you like this
![grafik](https://github.com/user-attachments/assets/5024b6d8-3ac1-4168-a15c-548716ddcf6f)

But as you are using wallabag.it you would need to wait until my config is the next release AND this release is installed on wallabag.it. :-(

2.)
The `<ul>` element in your second issue doesn't show up in FulltextRSS and wallabag. And I have no idea yet, why. Maybe I can look on it next week.

**Comment by QuAzI** [comment]
> I can make it visible, but not hidden behind the spoiler line.

It would be the best option for reading as I prefer to read from an e-ink reader
Thanks a lot

**Comment by HolgerAusB** [comment]
@j0k3r, @Simounet, @yguedidi, @fivefilters, @Kdecherf 

I fixed problem one but I can't understand, why the `<ul>` element from second post is not fetched. Neither on wallabag/wallabagger nor on Fulltext-RSS.

I got this with curl:

```html
<p>
   ÐŸÑ€Ð¾ ÑÐ°Ð¼ Obsidian Ð½Ð° Ð¥Ð°Ð±Ñ€Ðµ ÑƒÐ¶Ðµ Ð¿Ð¸ÑÐ°Ð»Ð¸, Ð½Ð°Ð¿Ñ€Ð¸Ð¼ÐµÑ€:
</p>
<ul>
   <li>
      <p>
         <a href="https://habr.com/ru/companies/alfa/articles/842228/" rel="noopener noreferrer nofollow">Notion ÑƒÐ¼ÐµÑ€, Ð´Ð° Ð·Ð´Ñ€Ð°Ð²ÑÑ‚Ð²ÑƒÐµÑ‚ Obsidian
         </a>
      </p>
   </li>
   <li>
      <p>
         <a href="https://habr.com/ru/companies/ozonbank/articles/838990/" rel="noopener noreferrer nofollow">Obsidian â€” Notion ÑÐ²Ð¾Ð±Ð¾Ð´Ð½Ð¾Ð³Ð¾ Ñ‡ÐµÐ»Ð¾Ð²ÐµÐºÐ°
         </a>
      </p>
   </li>
</ul>
<p>
   ÐÐ¾ Ð´Ð»Ñ Ð¼ÐµÐ½Ñ <strong>Obsidian Ð½Ðµ Ð±Ñ‹Ð» Ð·Ð°Ð¼ÐµÐ½Ð¾Ð¹ Notion</strong>, Ð¿Ð¾ÐºÐ° Ñ Ð½Ðµ Ð½Ð°ÑƒÑ‡Ð¸Ð»ÑÑ ÑÐ¸Ð½Ñ…Ñ€Ð¾Ð½Ð¸Ð·Ð¸Ñ€Ð¾Ð²Ð°Ñ‚ÑŒ ÐµÐ³Ð¾ Ð½Ð° Ð²ÑÐµÑ… ÑƒÑÑ‚Ñ€Ð¾Ð¹ÑÑ‚Ð²Ð°Ñ… Ð±ÐµÐ· ÑÑ‚Ð¾Ñ€Ð¾Ð½Ð½Ð¸Ñ… <s>ÐºÐ¾ÑÑ‚Ñ‹Ð»ÐµÐ¹</s> ¿Ñ€Ð¾Ð³Ñ€Ð°Ð¼Ð¼.
</p>
```

Could someone explain this, please.

**Comment by HolgerAusB** [comment]
arrrr, the body-selector was wrong
