### ISSUE TITLE
smh.com.au

### ISSUE THREAD

**Issue by yue-dongchen** [fivefilters/ftr-site-config#1442]
Sample article: https://www.smh.com.au/politics/federal/burke-to-sign-off-on-every-gazan-refugee-granted-new-humanitarian-visa-20241014-p5ki7u.html.
Problem: unwanted extra elements are included.

---
f43.me results:

The body should begin at "Gazan refugees must be".
![Screenshot from 2024-10-16 15-09-57](https://github.com/user-attachments/assets/9e573972-be87-4afd-8403-fd9310e69140)

---
The lines "Loading" should not be included, which presumably correspond to instances of "Related article" that do not belong to an article's actual content by the author.
![Screenshot from 2024-10-16 15-10-23](https://github.com/user-attachments/assets/c69c22a9-83ad-4dd4-b1c1-41d683eb8e17)

**Comment by HolgerAusB** [comment]
@yue-dongchen I am not sure, if you are writing in the right place. You mentioned f43.me which is more related to Graby and wallabag. This works slightly a small bit different as Fivefilter's FulltextRSS, whilst they are using the same config-files. Or you should name the product, you try to fetch the article.

So, if you are failing to fetch any site with wallabag, you should open issues at [wallabag/wallabag](https://github.com/wallabag/wallabag).

I fixed the config for smh and you may try again with FulltextRSS. For self-hosted wallabag you need to download the new config to  `vendor/j0k3r/graby-site-config/` and clear cache.

**Comment by yue-dongchen** [comment]
@HolgerAusB Thanks for the direction. I was under the false impression that Wallabag and Graby preferred rules to be modified upstream first. I realise now that reporting them directly to Wallabag would more sense.

I will try running Wallabag tomorrow on my local machine and sort of #1443 and #1443 . That was very generous of you to fix SMH.
