### ISSUE TITLE
haaretz.com

### ISSUE THREAD

**Issue by yue-dongchen** [fivefilters/ftr-site-config#1443]
1. The authors are not extracted into the metadata.
2. Images should not be omitted.
3. The following should be omitted — 
```
<div class="undefined hy"/>
<div class="undefined em bu afn cy dj ash ars any abh">
<form>
<div class="v">
<div class="a oj ex eg cs fk ek e">
<h2 class="nq fg hi al am ars">Israel At War: Get a daily summary directly to your inbox</h2>
</div>
<div class="eo zd asi asj po ask asl pp pq">
<div class="f en">
<div><label for="0.8578071061642937" class="gx a ex fa ez f bu dj fg hi al am aio kq xi xj asm xl xm asn ok ol aso acg ro rp asp acf asq aig fk qd qe ka kb xu xv xw xx asr ass ya yb yc yd ast asu">Email <abbr class="asx at" title="Required"><sup>*</sup></abbr></label></div>
<label for="0.8578071061642937" class="gx a ex fa ez f bu dj fg hi al am aio kq xi xj asm xl xm asn ok ol aso acg ro rp asp acf asq aig fk qd qe ka kb xu xv xw xx asr ass ya yb yc yd ast asu"><input aria-describedby="0.19538229391884654" data-test="input" class="ew jn abo f gx he aib" id="0.8578071061642937" type="email" value="yuedongchenyy@gmail.com"/></label>Please enter a valid email address</div>
<button class="ex abl abm abn gx hy nq abo dj du bu abp abq gv gu gy gz ha abr asy asz ahp abu abv he hd abw ata atb hk abz aca hc hb acb atc atd ace ro rp acf ok ol acg xl xm ab xi xj rh acj ja ate sf rv en fg hi al am j atf atg ath agq ags agt fk ed acm acn aba abb" data-test="button" type="button">Sign Up</button></div>
</div>
</form>
<div id="newsletterRegForm00000180-ad99-d8e5-addb-edd9ddc70000DialogWrapper"/>
</div>
```
4. The following should be omitted — `<h2 class="at my">Click the alert icon to follow topics:</h2>`

Sample HTML files prepared using [SingleFile](https://github.com/gildas-lormeau/SingleFile), with a Haaretz subscription (articles are hidden behind paywall)
- https://yuedongchen-public.s3.us-east-005.backblazeb2.com/Issue+reports/haaretz.com+site+config/Four+Reported+Killed+After+Israeli+Strike+Sparks+Fire+in+Central+Gaza+Displaced+Persons+Camp+-+Middle+East+-+Haaretz.com+(16_10_2024+3_48_38+pm).html
- Alternate layout for some articles: https://yuedongchen-public.s3.us-east-005.backblazeb2.com/Issue+reports/haaretz.com+site+config/Gunfire+Here%2C+Aerial+Bombing+There_+Israel+Steps+Up+the+Gaza-fication+of+the+West+Bank+-+Twilight+Zone+-+Haaretz.com+(16_10_2024+3_40_14+pm).html

**Comment by yue-dongchen** [comment]
The existing pattern `//div[contains(@id, 'newsletter')]` does not work to strip `<div class="bu afn cy dj ash ars any abh" id="newsletterRegForm00000180-ad99-d8e5-addb-edd9ddc70000" data-test="newsletter">`. I don't know how to form an XPath for it.

Remedy to additional problem not identified above: Add `strip: //div[@data-test="tags"]`.

**Comment by HolgerAusB** [comment]
@yue-dongchen this one is a bit more difficult because of the paywall. Maybe I find some time at the weekend to look on it.

Once again, with which product (version) are you trying to fetch articles?

**Comment by yue-dongchen** [comment]
The paywall should be irrelevant, as the use case is the following: Wallabag has the capability to receive HTMLs from the user's browser (see https://github.com/wallabag/wallabag/issues/1525). A subscribed reader would send the HTML to the service for processing.

**Comment by yue-dongchen** [comment]
Maybe extraction rules for paywalled-sites should not be included in this repo, as Full-Text RSS as a product can only obtain content via direct fetching. In that case, it should proceed in graby-site-config, since that is supposed to be a source-agnostic (whatever HTML it receives) module.

**Comment by HolgerAusB** [comment]
the fivefilters repo is the upstream for graby and wallabag. However, there are several unique config parameters for wallabag, which are nevertheless are stored in fivefilter's config.

So that is no problem. And for paywalled sites you can use wallabagger browser plugin (activate 'Retrieve content from the browser' in plugin settings). So there is might be a need for a site-config, too. And if the login is not to complicated, wallabag UI can store your credentials and log you in, if you are trying to fetch an article.

**Comment by yue-dongchen** [comment]
Yes, I was referring to the Wallabagger plugin but forgot its name. There already is a config file from FiveFilters from years ago, when Haaretz does not seem to have been hard-paywalled.

The problems outlined above are the outcome of using Wallabagger to send content to Wallabag. Thanks for your prompt merging with regard to the other two newspapers. Can I ask you as to the method you use for testing ftr-site-config files?

**Comment by HolgerAusB** [comment]
@yue-dongchen 

- when using wallabagger: the title is taken from the `<title>` node. No chance to change by config. But you can do this manually within wallabag UI
- when using wallabagger to grab content, the author and date fields are ALLWAYS empty, no chance to fix that with a config. The wallabag or Graby devs need to find a way to implement this. I already wrote an issue about that.
 
I registered with haaretz, so I get 6 free articles a month. So I could fix your first article. The second one is for paying subscribers only, but I think it should work, too.

Please copy/replace this [draft version of the config](https://github.com/HolgerAusB/ftr-site-config/blob/haaretz/haaretz.com.txt) to your wallabag instance at vendor/j0k3r/graby-site-config/

Don't forget to clear wallabag's cache every time you change something at the config before trying the next wallabagger fetch:

`sudo -u www-data bin/console --env=prod cache:clear`

PLEASE REPORT, if the changes to config are working or not, so I can commit them to the main repo

**Comment by HolgerAusB** [comment]
> Can I ask you as to the method you use for testing ftr-site-config files?

I am using a self-hosted wallabag and a self-hosted [FulltextRSS (FTR)](https://ftr.fivefilters.net/) server with a paid license. As the admin page of FTR offers an in-browser editor for site configs, I am writing my configs there and testing them at first with FTR.

As FTR don't have the possibility to fetch paywalled pages, that doesn't help with haaretz at all. So your SingleFile versions helped here.

After a config works in FTR I symlink the config-file to the wallabag path, I mentioned above. Then I test to fetch the article with wallabag UI and/or wallabagger. Most times that works without changes. But unfortunately FTR and wallabag/Graby do not always behave 100% the same. As a result, additional adjustments are sometimes necessary to make it run on both systems.

**Comment by yue-dongchen** [comment]
Danke sehr für den Hinweis und die offenbar geeignete Lösung der ersten Layoutvariante. Ich bekam leider Schwierigkeiten beim Einrichten der Docker-Container für Wallabag. Und nicht zuletzt befinde ich mich gerade im Zuge meiner Sekundärschulabschlussprüfungen, deswegen habe ich wenig Zeit.

Mittlerweile kann ich dir aber gerne meine Login-Details überlassen. Durch den Link in meinem Profil gelangst du an meine E-Mail sowie Signal.

**Comment by HolgerAusB** [comment]
I don't think, that it is necessary to send me your credentials. I think the config is working for at least these two designs.
