### ISSUE TITLE
phys.org extraction

### ISSUE THREAD

**Issue by tbelbek** [fivefilters/ftr-site-config#1490]
I am trying to create a ruleset for phys.org, but it seems the custom site filter is not parsing that at all. This is the sample url;

https://phys.org/news/2024-11-dna-evidence-rewrites-told-stories.html

And this is the filter I created;

title: //meta[@name='description']/@content
date: //meta[@property='article:published_time']/@content
author: //meta[@name='author']/@content
body: //div[@class='article-gallery lightGallery']/following-sibling::p | //div[@class='article-gallery lightGallery']/following-sibling::h2 | //div[@class='article-gallery lightGallery']/following-sibling::ins/following-sibling::p
strip: //script | //style | //ins | //iframe | //div[@class='article-gallery lightGallery']/following-sibling::div

And the engine returns 200 for each request I made. Can someone have any ideas?

**Comment by HolgerAusB** [comment]
Hi @tbelbek,

- please post config drafts or logfiles within a codeblock (`<>`-Button or three \`\`\` before and after the block). So it is better to read
- you should use lower case attributes like `@class` or `@property`, except the source website is using uppercase
- please tell which product you want to use this config for and which version. Sometimes a config file must be justified to work with FiveFilters FullText-RSS (FTR) and with wallabag.

If a website doesn't deliver anything you can check:
- Try to curl the article and inspect the retrieved html code for hints
- Try to set a different User-Agent
- If it is not a 200, it could help to set `prune: no` and/or `tidy: no`

In your case, I don't see a need of a body selector (I had only a quick view) This simple line delivers a shiny excerpt with FTR. Just setting the user-agent and everything is fine, author and date field included.

```yml
http_header(user-agent): Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0
```

**Comment by tbelbek** [comment]
Hello again, 

I am sorry about missing the format, I will be more careful. Thanks for the kind warnings. The capital letters are also a result of not using the necessary markdown.

I use a selfhosted FiveFilters Full-Text RSS 3.8 docker image on my server.

I tried curl, but it gave me a security warning with an 200, basically "You are blocked, contact admins" page. Then I added the user agent to the curl command, and it was successful. I got a full page so I changed the filter to this;

```
title: //meta[@name='description']/@content
date: //meta[@property='article:published_time']/@content
author: //meta[@name='author']/@content
http_header(user-agent): Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
```

Unfortunately it is still not being parsed. So is there any debug steps I can take in that situation?

**Comment by HolgerAusB** [comment]
@tbelbek this user-agent indeed is not working, try mine above. And as I said, for FTR 3.9.13 no need for selectors for author, title or date

**Comment by tbelbek** [comment]
Well.. I was creating the filter on custom folder. Instead, I added your user agent and put the filter to the standard folder and Voila! Started working. Now I created a PR, and thanks for the quick help!

**Comment by tbelbek** [comment]
Most probably I forgot the cache, but anyway it is merged and I will be able to use that with the standard folder by default. Thanks for the instant approval 💯
