### ISSUE TITLE
create a config for blog.google.com

### ISSUE THREAD

**Issue by ntimo** [fivefilters/ftr-site-config#212]
Hello,
can you create a config for the blog.google.com site? Please

Thank you,
Timo

**Comment by j0k3r** [comment]
You can do it on your own http://siteconfig.fivefilters.org/grab.php?url=https%3A%2F%2Fwww.blog.google%2Fproducts%2Fhome%2Fmake-yourself-home-google-home%2F :)

**Comment by ntimo** [comment]
@j0k3r But because the site is not https it can't load the content correctly so this does not work.
