### ISSUE TITLE
outlined words get censored on psychologytoday.com

### ISSUE THREAD

**Issue by anarcat** [fivefilters/ftr-site-config#251]
[This article about Richard Stallman](https://www.psychologytoday.com/articles/201611/the-sorcerers-code) is really weird to read on parsed content, because all the "dotted underline" words are just removed from the output. I reproduced this on the [test site](http://f43.me/feed/test).

The last sentence of the second paragraph should read like:

> If you’ve heard of open source (free software’s practice sans its **moral** stance) or Linux (really GNU, plus a program called Linux), you can thank Stallman.

(Emphasis on the removed word added.)

Instead it is:

> If you’ve heard of open source (free software’s practice sans its stance) or Linux (really GNU, plus a program called Linux), you can thank Stallman.

Thanks!

**Comment by fivefilters** [comment]
Hi, that's strange. The external parser on that site does preserve it. Not sure what the difference is. I can't see anything strange in the site config files for psychologytoday.com to be stripping those elements. And they're preserved correctly in Full-Text RSS: http://ftr.fivefilters.org/makefulltextfeed.php?url=https%3A%2F%2Fwww.psychologytoday.com%2Farticles%2F201611%2Fthe-sorcerers-code&max=3

**Comment by anarcat** [comment]
i always get the strange stuff. :p

**Comment by j0k3r** [comment]
This issue was moved to j0k3r/php-readability#23

**Comment by anarcat** [comment]
okay well, i thought that since i reproduced the problem on the external website, the next step was to file an issue here. i was following [this guide](http://doc.wallabag.org/en/master/user/errors_during_fetching.html#how-can-i-help-to-fix-that) - maybe i misunderstood something or the guide can be clarified?

**Comment by j0k3r** [comment]
Yeah maybe we should clarify few things

**Comment by anarcat** [comment]
wait so this is fixed right?
