### ISSUE TITLE
create config for theverge.com

### ISSUE THREAD

**Issue by anarcat** [fivefilters/ftr-site-config#267]
[this article](http://www.theverge.com/2017/1/12/14244634/signal-app-secure-messaging-trump-surveillance-encryption) doesn't render properly at all [here](http://f43.me/feed/test).

testing on [this site](http://siteconfig.fivefilters.org/grab.php?url=http%3A%2F%2Fwww.theverge.com%2F2017%2F1%2F12%2F14244634%2Fsignal-app-secure-messaging-trump-surveillance-encryption) would lead me to think a good start would be the Xpaths:

* `//div[contains(concat(' ',normalize-space(@class),' '),' l-wrapper ')]//div[contains(concat(' ',normalize-space(@class),' '),' l-segment ') and (contains(concat(' ',normalize-space(@class),' '),' l-feature '))]`
* `//div[contains(concat(' ',normalize-space(@class),' '),' c-entry-hero__content ')]`

but i'm not sure how to add *two* xpaths at once?

**Comment by fivefilters** [comment]
Thanks for the report. We've updated the site config file. Hopefully this fixes the issues: https://github.com/fivefilters/ftr-site-config/blob/master/theverge.com.txt

To combine two XPaths you can do the following:

    body: //div[...] | //article[...]

If the elements are both `<div>` elements. You can also do the following

    body: //div[contains(@class, 'xyz') or contains(@class, 'xyz')]
