### ISSUE TITLE
COPYING/license file missing

### ISSUE THREAD

**Issue by stesie** [fivefilters/ftr-site-config#58]
Hi,

I think it'd be good if you'd provide a COPYING file clearly stating the license of this work.

After all I consider using these files as well but I'm a bit confused regarding legal situation
- on http://help.fivefilters.org/customer/portal/articles/223153-site-patterns you say _in the same spirit, have made available our own additions for anyone to use_
- likewise on http://www.keyvan.net/2011/03/content-extraction/
- from http://fivefilters.org/content-only/ however you can either download old versions (for free; licensed AGPL) which don't have patterns included or you can pay (and get the patterns)

So after all it sounds like "hey, it's public domain" ... right?
If so, could you please add a COPYING file stating so :-)

cheers
  ~stesie

**Comment by fivefilters** [comment]
Hi Stesie, yes, I intended it to be public domain (that's how I interpret Marco's original post too). AGPL only applies to the Full-Text RSS code (whether paid or free).

I will look to add the COPYING file. Won't do so right now as I have to see if it impacts the automatic updates which pull in files form this repository.

**Comment by jcharaoui** [comment]
Public domain (aka [CC0](https://creativecommons.org/publicdomain/zero/1.0/)) is the least restrictive license of all, so it should not have any negative impact on any downstream products even if they are made available under a more restrictive licence.

**Comment by fivefilters** [comment]
We've now added a [LICENSE.txt](https://github.com/fivefilters/ftr-site-config/blob/master/LICENSE.txt) file stating the files are released to the public domain with the URL of the CC0 page for more inforation.
