### ISSUE TITLE
ad.nl and related sites, it seems, no longer work

### ISSUE THREAD

**Issue by janboddez** [fivefilters/ftr-site-config#682]
Using the latest Wallabag Docker image, sites published by DPG Media no longer work: the cookie wall isn't automatically bypassed. (Ex. from source: http://www.ad.nl/ad/nl/10444/Offside/article/detail/4043834/2015/05/31/Dani-Alves-voetbalt-met-drol-op-zijn-hoofd.dhtml)

Stumbled upon this by trying to copy and adapt settings for ad.nl and parool.nl to demorgen.be (and, perhaps hln.be), as they should all be using the same cookie wall technology.

It'd be awesome if these could be fixed/added.

Possible additional test URL: https://www.demorgen.be/nieuws/locked-and-loaded-trump-dreigt-met-militaire-actie-tegen-iran-olieprijzen-schieten-omhoog~b82ff8c9/

Also affected: volkskrant.nl, see ex. https://www.volkskrant.nl/nieuws-achtergrond/privacywaakhond-verbiedt-cookiemuren-op-websites-ja-ook-die-op-volkskrant-nl~b7dab7ee/

**Comment by j0k3r** [comment]
Looks like you can bypass the cookie popup using this in your siteconfig: `http_header(cookie): pws=functional; pwv=2`

This might be applied to all related sites you are mentioning

**Comment by janboddez** [comment]
Ah, I'd been trying with just the `pws` cookie, but couldn't get it to
work. Will definitely look into it again later.

**Comment by janboddez** [comment]
I'm definitely able to get demorgen.be to work with the following settings:
```
strip: //aside[@data-element-id='article-element-editorialtips']

http_header(cookie): pws=functional|analytics|content_recommendation|targeted_advertising|social_media; pwv=1
```
Confirmed with just functional and analytics cookies, too, though you'll get a missing embedded content notice (which could be stripped out, I guess) even though that content isn't included with the above settings, either.

Haven't tried the other sites, yet.

Would a pull request help?

**Comment by j0k3r** [comment]
Yup you can submit a PR then
