### ISSUE TITLE
inpact-hardware paywall

### ISSUE THREAD

**Issue by X-dark** [fivefilters/ftr-site-config#696]
Hi,
I am trying to add https://www.inpact-hardware.com and most specifically the paywall part. It seems the login form is submitted as a json payload and I don't understand how to configure it. Any hint?

**Comment by j0k3r** [comment]
Never got that way to handle login for now

**Comment by Pofilo** [comment]
They have a new version of their website, maybe it changes the API too.

**Comment by j0k3r** [comment]
https://github.com/wallabag/wallabag/issues/4773
