### ISSUE TITLE
Website Arrêt sur Images has wrong paywall URL

### ISSUE THREAD

**Issue by yattoz** [fivefilters/ftr-site-config#781]
The connection URL in arretsurimages.net.txt should not be :
`http://www.arretsurimages.net/forum/login.php`
Instead, it should be:
`http://www.arretsurimages.net`
The login form is now directly accessible from the home page. Fields still have the same ids: `username` and `password`.
This may help fixing the paywall detection, although I can't test it by myself.

**Comment by Kdecherf** [comment]
Login has become complex and can't be handle by site-configs without additional logic in graby and cie, thus I removed it in #932

I think we can close this issue @j0k3r @fivefilters
