### ISSUE TITLE
Paywall Nextinpact new version

### ISSUE THREAD

**Issue by Pofilo** [fivefilters/ftr-site-config#792]
The website nextinpact has released a new version of their website and it seems articles cannot be extracted anymore.

**Comment by Pofilo** [comment]
@Simounet I saw (with a git blame) that you wrote the original version of the nextinpact rules. I tried multiple time to fix it without any success, do you know what is going wrong on this one ? (it's due to a new nextinpact version, but I can't figure out what's wrong now).

Thanks :) (and forget about it if you don't want, I'm just getting in touch with you because you wrote the original version)

**Comment by Simounet** [comment]
Hi @Pofilo ,
They are using JS client side to display the content. That's not ideal and difficult to parse than server side rendered HTML.

**Comment by Pofilo** [comment]
Thaks @Simounet for your answer.
I don't know if we managed to do it with other websites .. If it is too difficult, maybe we should delete the nextinpact parser as it will not work anymore. Don't you think ?

**Comment by j0k3r** [comment]
That link worked fine for me

https://www.nextinpact.com/article/30439/109208-ce-que-revelent-11-milliards-dannees-dexpansion-lunivers

![image](https://user-images.githubusercontent.com/62333/92610276-d124ac80-f2b7-11ea-8b86-4eccc51e9678.png)

**Comment by Pofilo** [comment]
Hello,
Yes because it is a free article with no need to pass the paywall.
An article like [https://www.nextinpact.com/article/43609/android-11-disponible-en-version-finale-nouveautes-smartphones-eligibles](https://www.nextinpact.com/article/43609/android-11-disponible-en-version-finale-nouveautes-smartphones-eligibles) will not return all the article (as if you open it in a classical browser).

**Comment by j0k3r** [comment]
Ok I didn't know it was related to the paywall

**Comment by Simounet** [comment]
> 
> 
> Thaks @Simounet for your answer.
> I don't know if we managed to do it with other websites .. If it is too difficult, maybe we should delete the nextinpact parser as it will not work anymore. Don't you think ?

Yep. We can remove this one for now.

**Comment by Simounet** [comment]
Second thoughts about it. We should keep it if it's working for some articles. Maybe we should only remove the login information.

**Comment by Pofilo** [comment]
Good point, it is still working for "free" articles !

**Comment by j0k3r** [comment]
☝️ done

**Comment by Simounet** [comment]
Perfect, if it's ok for you @Pofilo I think we can close this issue.
