### ISSUE TITLE
unable to parse zeit.de

### ISSUE THREAD

**Issue by Stef-L** [fivefilters/ftr-site-config#797]
It seems the last change (#773) to [zeit.de.txt](https://github.com/fivefilters/ftr-site-config/blob/master/zeit.de.txt) concerning cookie does not work anymore.
The cookie content now is a timestamp in format "2020-09-03T19:45:59.150Z".
I tried to just insert that instead of the previous fixed text, and it even worked on f43.me.
`http_header(Cookie): zonconsent="2020-09-03T19:45:59.150Z"`
Testwise changing the timestamp to August 3rd it didn't work.
So question: How can the date (and time?) set dynamically?

[Test-URL](https://www.zeit.de/kultur/2020-09/corona-demo-rechtsextremismus-berlin-verschwoerungstheoretiker-coronavirus/komplettansicht)

**Comment by fivefilters** [comment]
Hmm, does it work if you set it to a future date? (By the way, I don't think quotes should be used here.)

    http_header(Cookie): zonconsent=2022-09-03T19:45:59.150Z

**Comment by j0k3r** [comment]
If it works we should create a reminder in 2022-09-02 to update the date in the site config :)

**Comment by Stef-L** [comment]
I updated my installation with that file and it works now with date in 2022.
Many thanks for that idea, obviously it was too late for me to simply try that. ;)

**Comment by fivefilters** [comment]
@Stef-L Excellent! Thanks for opening the issue.

@j0k3r Haha! Really hope that's not what ends up breaking the next extraction with the site!
