### ISSUE TITLE
florian-casse.fr does not parse

### ISSUE THREAD

**Issue by andre-faria** [fivefilters/ftr-site-config#798]
Used wallabag to add it and it didn't fetched, so I came here because of `http://siteconfig.fivefilters.org/` this tool.

I did the selection but it keep not parsing, any thoughts ?

`https://florian-casse.fr/clear-dns-cache-on-vcsa-6-5-and-later/`

```
# Generated by FiveFilters.org's web-based selection tool
# Place this file inside your site_config/custom/ folder
# Source: http://siteconfig.fivefilters.org/grab.php?url=https%3A%2F%2Fflorian-casse.fr%2Fclear-dns-cache-on-vcsa-6-5-and-later%2F

body: //div[contains(concat(' ',normalize-space(@class),' '),' entry-content ')]
test_url: https://florian-casse.fr/clear-dns-cache-on-vcsa-6-5-and-later/
```

**Comment by j0k3r** [comment]
> Request throw exception (with no response): cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

Looks like an issue related to the server running f43.me.

From the server itself, I got:
> \# curl -i https://florian-casse.fr/clear-dns-cache-on-vcsa-6-5-and-later/
curl: (60) SSL certificate problem: unable to get local issuer certificate
> More details here: https://curl.haxx.se/docs/sslcerts.html
> 
> curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

Everything is up to date (unless the Ubuntu distrib).

**Comment by HolgerAusB** [comment]
Meanwile the browser throws a certificate issue: wrong domain name
last post is nearly two years ago. So i close this issue.
