### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by andre-faria** [fivefilters/ftr-site-config#799]
I'm trying out to do the filters with the your tool `http://siteconfig.fivefilters.org/`, how can I contribute when it work?

This filter below worked, its for virten.net
```
# Generated by FiveFilters.org's web-based selection tool
# Place this file inside your site_config/custom/ folder
# Source: http://siteconfig.fivefilters.org/grab.php?url=https%3A%2F%2Fwww.virten.net%2F2013%2F04%2Fintel-cpu-evc-matrix%2F

body: //div[contains(concat(' ',normalize-space(@class),' '),' post-single ')]
test_url: https://www.virten.net/2013/04/intel-cpu-evc-matrix/
```

**Comment by j0k3r** [comment]
Create a new file `virten.net.txt` with the content you found at the root level of that repo and then open a pull request

**Comment by andre-faria** [comment]
> Create a new file `virten.net.txt` with the content you found at the root level of that repo and then open a pull request

Thanks, done
