### ISSUE TITLE
Specify title in site config file

### ISSUE THREAD

**Issue by andre-faria** [fivefilters/ftr-site-config#869]
In this example Wallbag can extract article without a specific site config, but It can't set the title, there is a way to specify where is the title in site config?

![image](https://user-images.githubusercontent.com/12632275/112221791-a2907280-8c06-11eb-9049-1717a8b58266.png)

![image](https://user-images.githubusercontent.com/12632275/112221233-f8184f80-8c05-11eb-9a47-66d817518c2d.png)

http://siteconfig.fivefilters.org/grab.php?url=https://www.kapilarya.com/fix-you-cant-access-this-shared-folder-because-your-organizations-security-policies-block-unauthenticated-guest-access

```
# Generated by FiveFilters.org's web-based selection tool
# Place this file inside your site_config/custom/ folder
# Source: http://siteconfig.fivefilters.org/grab.php?url=https://www.kapilarya.com/fix-you-cant-access-this-shared-folder-because-your-organizations-security-policies-block-unauthenticated-guest-access

body: //div[contains(concat(' ',normalize-space(@class),' '),' entry-content ')]
test_url: https://www.kapilarya.com/fix-you-cant-access-this-shared-folder-because-your-organizations-security-policies-block-unauthenticated-guest-access
```

**Comment by fivefilters** [comment]
In Full-Text RSS the `<title>` element will be used if there are no explicit title elements specified. That should be the same thing you see in your browser tab when the page loads. I assume Wallabag would try to do the same. If you're able to test, you can try being explicit about it with the following:

    title: //title

or to select the `<h1>` element:

    title: //h1

You can try adding these one at a time, to the site config file to see if it pulls in the title.

**Comment by andre-faria** [comment]
Hello, I specified the title: //h1 and title: //title one at a time and It didn't work, I will update my Wallabag instance and try again, thanks.

**Comment by HolgerAusB** [comment]
@andre-faria do you still have problems here?

- If yes, please explain more details (how exactly are you catching articles in wallabag), because my wallabag 2.6.8 is catching well including the orignial title. And Fultext-RSS is doing also a good job without a config.
- If no, please close the issue

**Comment by andre-faria** [comment]
Hello, how are you?

Well, I retired my personal server 2 years ago, so I'm not using Wallabag and TT-RSS anymore. So I really can't answer your question, if you want, you can close this issue.

Thank you very much.

Planning a new server for future, but now now.
