### ISSUE TITLE
faz.net paywall articles shows payment-hint instead of the teaser as content

### ISSUE THREAD

**Issue by HolgerAusB** [fivefilters/ftr-site-config#925]
faz.net has free articles and f+ articles behind a paywall. For these f+ articles, apart from the headline, only a short teaser is displayed on the page and then a notice that you should pay 2.95 EUR per week to continue reading.

In this case, fullt-text-rss only takes the payment terms as content and not the teaser.

Can someone please adjust the site-config so that the teaser is taken over for f+ articles? Gladly also with a short (German) hint that you can read more only with a subscription.

examples:

free:
[http://ftr.fivefilters.net/makefulltextfeed.php?url=https%3A%2F%2Fwww.faz.net%2Faktuell%2Fsport%2Folympische-winterspiele%2Fdeutsches-team%2Fkatharina-althaus-holt-olympia-silber-in-china-im-skispringen-17782373.html&max=3](http://ftr.fivefilters.net/makefulltextfeed.php?url=https%3A%2F%2Fwww.faz.net%2Faktuell%2Fsport%2Folympische-winterspiele%2Fdeutsches-team%2Fkatharina-althaus-holt-olympia-silber-in-china-im-skispringen-17782373.html&max=3)

f+:
[http://ftr.fivefilters.net/makefulltextfeed.php?url=https%3A%2F%2Fwww.faz.net%2Faktuell%2Fpolitik%2Fausland%2Fdie-bergbaustadt-broken-hill-in-australien-setzt-auf-solarenergie-17735957.html&max=3](http://ftr.fivefilters.net/makefulltextfeed.php?url=https%3A%2F%2Fwww.faz.net%2Faktuell%2Fpolitik%2Fausland%2Fdie-bergbaustadt-broken-hill-in-australien-setzt-auf-solarenergie-17735957.html&max=3)

Since I host fulltext-rss on my own server, the required lines for the config would also be fine for me

**Comment by fivefilters** [comment]
Thanks for letting us know. We'll see what we can do to improve that. 👍

**Comment by HolgerAusB** [comment]
as I am a beginner, it took me quite while to understand, that I just need to strip some more advert-containers. Finally a managed to get it work. I will test the full-text-feed for a week and make a pull request next weekend. Is that ok? would be my first pull request to an active project.
