### ISSUE TITLE
Suggestion for nytimes.com.txt

### ISSUE THREAD

**Issue by nwa573** [fivefilters/ftr-site-config#942]
I wanted to suggest adding this to nytimes.com.txt:
`strip: //section[contains(@role, "complementary")]`
In an article like https://www.nytimes.com/2022/02/27/business/economy/price-increases-inflation.html that removes the  "Understand Inflation in the U.S." and "Inflation F.A.Q." boxes, which aren't part of the main body.

**Comment by j0k3r** [comment]
Feel free to open a PR!

**Comment by nwa573** [comment]
I attempted a pull request but am not sure whether I did it correctly!

**Comment by j0k3r** [comment]
Why did you close it?

**Comment by nwa573** [comment]
I didn't even realize I had; it's my first time opening and I must have screwed up. Anyway, I just opened a new one.
